services:
  postgres:
    image: postgres:17
    container_name: georgette-postgres
    ports:
      - "54323:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - georgette_pg_data:/var/lib/postgresql/data

volumes:
  georgette_pg_data:
